sudo: required
branches:
  only:
  - main
env:
  global:
  # GIT_UID
  - secure: 3Agk7jS9tTkOe9M96VdXvC5sJhEkp7QHKTdhXfvlD6vJW0Gdx782Ort7gKFarES88fWOr5J1+5cHPJY0jW4iW1b9wavUJsxcB0Hh9IBT70Zg9LSBnMacY7rUnL4lJwisOSw/lgnrixjfrnRpsSCogZbLtn0Iy0BP4G3GZ83zktppcMk/06bPJwGv09KhVh3aKuf4VRFW8uG0R5eLI8gyJADULVAhBfNRMcWnOEEr+3XlloSc2+adPsTtnA8YFyzxOk8lvvLOqSOf9jmyK7lQ/oP7fwjpa6W3qH4luh9aet4dWi++wH9XZjN9fXHZGfUZhpxAnhdZ8s00U9JIB7GPm9HrYCNz/6ChSCpREwBNM0Wb05KVmCKH4hX47G/RxG5gc91oIjQ0gdcJrboU7ZmMB/KHgDm5mVG2+XqlkZEMiiS5Oj/ILMFuCoPCmTQhAVdllpDXk5ggjb0WsHIFTP9b3RAgtAYY3BFpNyqITDDOvPHl8D3acAkWiiCSdNqf9Nda/617HXfhps33+OBVuEPfNR510WT4xw5zTru0+KG6RgKygMuGEEcWQQYfTHFo3h3R5AD9QsR+wqQPin+5el5dihuWvsJuwaDE8KinBj4wY0fyjuLS8vg3qC2b6YVnqz6BCtZYuzZGuOkuHiO8XBkEKHPCAn/bJ1G2BqLFzdd79Nk=
  # GIT_TOKEN
  - secure: Ny0O+RKgLuZO4B/TW20r6Ti+YUjRn49K7AFTtnuBAV2JEtc3aWobmLjHuQyfVw2SxfXY8MQDDK1rN2/w9mg683B3Ew7lnBnuwBupWqoajdT5ZRdOZtF/f9gEJ30Ofw6qvoCx/w2HqRjew5X09pavcz1yogYQY2+oHRWRYjRL0uSiVRxHS1WkpcaW8xfcvf5Wv7psEuZ8aHMgmXc17zP4h25U3Ke/Oi72u10dD1zqYXHe0zi1gU4UjB1KUmKtJ9h26vDWCxDBk2YWgimUDWNgYsD+zqwn0DfqMZPUaQ0S1TSSUzsdC5xYSKteEwcGJ6XuhR6yK4n1b20qUPB3k8Aa/Xq++EWuIEdogKMAA22Ra6QFNpny7Ku+/7WRc0F6Wa2RVbhWBRWCpaTA1z7kXbpdgxT+eKGXM3bPraVQRtbta1WqZcqg+WRFvDf3lL0Mj73FyzKaxoRYAxhQvwVIVcLKFRMLG2SwYmj746GXwfw4/dP2rCTOBmO5eh1vMUBW23jMYXJBO8bEDKXNlnZGgdf/geVhbTBxSbZNESbNX6cWxfvcjd8vWpy47OOUMXZ+tE21ZqYDuvbHtilQDDD3DXVBb+dVxuT9OSG5oTD1vqMgh8pjSpo/es3oTAn7aQnsThDNBmeRvCO2n2VAhRJ/rMkObsfATl6zbkL/Z5d/Z6cO0qo=
  # GIT_USER_NAME
  - secure: PkpweVKwhK3GgF3LTVxvYRBBLdGhXrs9YmwdwW7KQNoLl1fDSfTCGzhfFv+onRG3g0s1Of71onIu3/UiwxTR52MEgiUBIA7kQPYndeDwQYlyxJLPF8zUiCg6NNsVzS1n20vUQiwBUZxBn25owj/Ipes6NnZ5ff4/FWOxG752QDwxxpzJNg28BsG9ndtbks5EAw/C2zy7x1uG6O1nl3jaxUeF1ECSv6BjaNGzTneBjqMxglWlCK+Gcjdr9ZTWm2hNiskG+pM8qG4KDwelRmebgV+4cg+X7f6W7vXZoayR/MxPmr6rqTTJYNsEhIl0kJcLeq0DWeCa61IFI/kR0FIxgF4NFtfrkjv2bavbakAW9o0XLUVKaGTY3MSwvMDdB3oXTXcNWso4/ok70+Bwed7FarZ3aekPXi4tGohuIXUb85hiDRo28iQuERzQ+FU3Gh4kYbQmInqKfa/yMqw7ALuuM6/Mo9lgblS1UuDxgjRZsdXaM0urkhIsZ7UEeOVLSvIEdlBc+mqmk+p7QltufC4xnaKZfxz+qZevvB/fE+AgKURzma9a+ewQvLDDLEPiO3/V6b+DS9HnDkTRz1EXOlS6tmpXGZTI7NO9YvjFm16Di5zPQe9LoV6P22tOvV8k59+t0sYutQB/9x6Qd48H62A5WXoJoZ5kcPTbDOg9pLOi3KI=
  # GIT_USER_EMAIL
  - secure: 6oYNTWCIyKm9asatrYuhJViooFlYkhh7KI+YqPa2/IqQ3hlx2urnMk9w54O4gAMpjK4E52jQ39+Emk33/qKAPWODv5JpYrQ8UyAmKpmOU62epp7LQVe4ZE+N68Cm1KnGEw5UTtcmAIuGM2j+S07uiyjhUKIFfsFvocg02fcaMFZJy9ad4NCRQYksGwLqoiuII0szXX4eODLAZmPP+/rjAfXe3tMm87J1vqgjmWXYYKfO73QFGE2MX8qe4jtaI0rcp4s5hExkLw9AYBrpDx6cbDHxKJ1Dr89ZNDb3iRR4j09epY+yRT0j1UPgbc/I+Hz3fHZUp6UX1UcOS4I0dNccU3g5jo5XEWsnEThPx3ottnJUPdTEKecACIxI07/7MmQAJ2qot2BNh/tScLO6Xcy8BJNpaHNTpLBXU3G7VTIsPcmKf9E6m7QVPq+6CBEduWOqBb11gdGpBjtrK6stGoewEWsXj9fIRPgBrz8Z0ByeWxgqHVpFK9E4BxK71QM1P8IY3DVu/usL3Zd/iRaPfxQRhoWdNcZ8Zdj4pyOsQ+U5O90ixbSVslcngxJqD/5srFSGG9Nh4nS2HPv60KflwkRfXp687Rwo6RIjYjDf9qFQ2U4JnrECP+7wVQNAnoRct5SyVrtGp6mFmfDBFopXEhyqfYaquobxLUuL0sl5zq5/PmQ=
notifications:
  email:
  - "{GIT_USER_EMAIL}"

services:
- docker
before_install:
- mkdir -p output
- docker pull asciidoctor/docker-asciidoctor
script:
- GUIDE_VERSION=`cat VERSION`"-${TRAVIS_BUILD_NUMBER}"
- echo ${GUIDE_VERSION}
- docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor      asciidoctor
  -D /documents/output DMRpp.adoc
- docker run -v $TRAVIS_BUILD_DIR:/documents/ --name  asciidoc-to-pdf asciidoctor/docker-asciidoctor  asciidoctor-pdf
  -D /documents/output DMRpp.adoc
after_error:
- docker logs asciidoc-to-html
- docker logs asciidoc-to-pdf
after_failure:
- docker logs asciidoc-to-html
- docker logs asciidoc-to-pdf
after_success:
- ./travis/deploy_to_gh_pages.sh
