sudo: required

# whitelist
branches:
  only:
    - main

notifications:
  email:
    - mjimenez@opendap.org

services:
  - docker                  

before_install:
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

# Name the file explicitly until we sort out the organization of the 'documentation'
# project.

script:
  # Inject the version information
  - GUIDE_VERSION=`cat VERSION`"-${TRAVIS_BUILD_NUMBER}"
  - echo ${GUIDE_VERSION}
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor      asciidoctor -D /documents/output DMRpp.adoc
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name  asciidoc-to-pdf asciidoctor/docker-asciidoctor  asciidoctor-pdf -D /documents/output DMRpp.adoc

after_error: 
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf

after_failure:
  - docker logs asciidoc-to-html
  - docker logs asciidoc-to-pdf


after_success:      
  - ./travis/deploy_to_gh_pages.sh